#!/usr/bin/env perl
#
# pre-inst-env script written in pure standard perl. Documented for
# Guix novices.

use v5.36;
use Cwd qw(realpath);
use File::Basename qw(dirname);

use Getopt::Long qw(GetOptions);
use Pod::Usage;

use utf8;
use open qw( :std :encoding(UTF-8));

our $VERSION = 1.0.0;

my $help = 0;

GetOptions(
  'help|?' => \$help
) or pod2usage(2);

pos2usage(-verbose =>, -exitval => 0) if $help;

my $script_dir = dirname(realpath(__FILE__));

unless (-d $script_dir) {
  die "Error: Unable to determine source directory.\n"
}

my $channel_path = "$script_dir/channel";

unless (-d $channel_path) {
    die "The channel directory doesn't exist...wait what!?\n"
}

$ENV{GUILE_LOAD_PATH} = "$channel_path" . 
  ($ENV{GUILE_LOAD_PATH} ? ":" . $ENV{GUILE_LOAD_PATH} : "");

$ENV{GUIX_PACKAGE_PATH} = "$channel_path" . 
  ($ENV{GUIX_PACKAGE_PATH} ? ":" . $ENV{GUIX_PACKAGE_PATH} : "");

if (!@ARGV) {
    pod2usage(
      -verbose => 1,
      -exitval => 1,
      -message => "Error: No command provided to execute.\n");
}

exec { $ARGV[0] } @ARGV
    or die "An error happened while executing '$ARGV[0]': $!\n";

__END__

=head1 NAME

pre-inst-env - A development environment launcher script.

=head1 SYNOPSIS

pre-inst-env [OPTIONS] <command> [args...]

=head1 DESCRIPTION

This script serves as a C<pre-installation environment> for Gnu Guix.
Its primary function is to set up the necessary environment variables, 
specifically C<GUILE_LOAD_PATH> and C<GUIX_PACKAGE_PATH>, to include a custom
channel's main directory (set in the C<.guix-channel> file) before executing
any subsequent command.

=head1 OPTIONS

=over 4

=item B<--help>

Display this help message and exit.

=back

=head1 ERRORS & EXIT STATUSES

The script exits with a non-zero status code if:
  - It cannot determine the script's directory path.
  - A command to execute is not provided.
  - The command fails to execute.
  - The channel directory is gone (has happened, don't ask :( pls)

=head1 AUTHOR & COPYING

Urutaú Limited <softwarelibre@urutau-ltd.org>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

=cut
